[[redirects]]
  from = "/survey"
  to = "https://c8t6ztfj4ah.typeform.com/to/nblWkc7m"

[[redirects]]
  from = "/yaml"
  to = "https://docs.diploi.com/reference/diploi-yaml"

[[redirects]]
  from = "/dev"
  to = "https://docs.diploi.com/building/remote-development"

[[redirects]]
  from = "/launch"
  to = "/"
  status = 301

[[redirects]]
  from = "/in"
  to = "/?utm=in"
  status = 302

[[redirects]]
  from = "/launch/astro"
  to = "/component/astro"
  status = 301

[[redirects]]
  from = "/launch/next"
  to = "/component/next"
  status = 301

[[redirects]]
  from = "/launch/sveltekit"
  to = "/component/sveltekit"
  status = 301

[[redirects]]
  from = "/ai"
  to = "/features/ai"
  status = 301

[[redirects]]
  from = "/devops"
  to = "/features/devops"
  status = 301

[[redirects]]
  from = "/blog/importing_from_lovable"
  to = "/blog/importing_from_lovable_and_github"
  status = 301

[[redirects]]
  from = "/blog/hosting_react_apps/hosting_react_apps"
  to = "/blog/hosting_react_apps"
  status = 301

[[redirects]]
  from = "/alternative/railway"
  to = "/alternative/to-railway"
  status = 301

[[redirects]]
  from = "/alternative/vercel"
  to = "/alternative/to-vercel"
  status = 301